# Site
name: "mleipzig."
title: "Matthew Leipzig's website"
description: "Matt's website."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "" # For GitHub Pages without project-specific subdirectory
disqus: "demowebsite"
email: "mleipzig@stanford.edu"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

include: ["_pages", "_projects"]
permalink: /:title # Changed here

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

authors:
  matthew:
    name: "Matthew Leipzig"
    avatar: assets/images/sam.jpg
    bio: "I write about statistics and causal inference. I also make cool coding projects in R."
    email: mleipzig@stanford.edu
    twitter: https://x.com/MattLeipzig
    github: https://github.com/mleipzig

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: matthew
      avatar: assets/images/sam.jpg
      image: assets/images/12.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  - scope:
      path: "_projects"
    values:
      layout: project
      title: "Project"
      permalink: /projects/:basename

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
