# Site SEO and various texts stuff
name: "Alan Brown"
title: "Alan Brown's Website"
description: "Alan S. Brown's personal portfolio website."

# Comment out below if you want to use this site's publication feature
scholar: "https://scholar.google.com/citations?user=vXPGwxkAAAAJ&hl=en"

authors:
  alan:
    name: "Alan S. Brown"
    avatar: "assets/images/pfp.jpg"
    bio: "I'm a lorem ipsum dolor sit amet, consectetur adipiscing elit, ommodo consequat."
    email: alanb@stanford.edu

# Advanced config below

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

# Site settings
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "" # For GitHub Pages without project-specific subdirectory
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

# Include files to be copied to the _site directory
include: ["_pages", "_projects"]
permalink: /:title

# Page variable defaults
defaults:
  # (posts should be automatically assigned to matt and a default image)
  - scope:
      path: "_posts"
    values:
      layout: post
      author: alan
      avatar: assets/images/pfp.jpg
      image: assets/images/12.jpg

  # (pages should be automatically assigned the page layout)
  - scope:
      path: "_pages"
    values:
      layout: page

  # (projects should be automatically assigned the project layout)
  - scope:
      path: "_projects"
    values:
      layout: project
      permalink: /projects/:basename

# Syntax
markdown: kramdown
highlighter: rouge

# Pagination for blogs (sad...library doesn't extend for other lists)
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.md,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
