 # Site SEO and various texts stuff
name: "mleipzig."
title: "Matthew Leipzig's website"
description: "Matt's website."

authors:
  matthew:
    name: "Matthew Leipzig"
    avatar: assets/images/sam.jpg
    bio: "I write about statistics and causal inference. I also make cool coding projects in R."
    email: mleipzig@stanford.edu
    twitter: https://x.com/MattLeipzig
    github: https://github.com/mleipzig

# Advanced config below

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

# Site settings
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: "" # For GitHub Pages without project-specific subdirectory
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"

# Include files to be copied to the _site directory
include: ["_pages", "_projects"]
permalink: /:title

# Page variable defaults
defaults:
  # (posts should be automatically assigned to matt and a default image)
  - scope:
      path: "_posts"
    values:
      layout: post
      author: matthew
      avatar: assets/images/sam.jpg
      image: assets/images/12.jpg

  # (pages should be automatically assigned the page layout)
  - scope:
      path: "_pages"
    values:
      layout: page

  # (projects should be automatically assigned the project layout)
  - scope:
      path: "_projects"
    values:
      layout: project
      permalink: /projects/:basename

# Syntax
markdown: kramdown
highlighter: rouge

# Pagination for blogs (sad...library doesn't extend for other lists)
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.md,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
